"""Single entry point. ``python -m qheart.cli <command>``.

One entry point, one config format, one results ledger. The reason is reproducibility
in the narrow sense that matters at judging time: every number in the report can be
regenerated by a command that is written down, and nobody has to remember which
notebook cell was run in which order. Notebooks are for looking at things; anything
that produces a reported number goes through here.

Commands
    schema      print the data contract
    models      print the model registry
    params      print circuit parameter counts and matched Control-C sizing
    budget      print the O(N^2) quantum-kernel cost estimate
    data        load, validate and cache the processed dataset
    audit       write data_audit.json/.md -- run this before modelling
    baselines   score all classical baselines
    kernel      precompute the Gram matrix, then score the quantum kernel SVC
    vqc         train and score the variational classifier
    control     score Control-C, sized from the circuit at runtime
    compare     aggregate the ledger, run McNemar + Holm, render tables and figures
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

DEFAULT_SEED = 20260830
PROCESSED = Path("data/processed/cardio_70000.parquet")
LEDGER = Path("results/runs/ledger.csv")


# ------------------------------------------------------------------ helpers
def _load_config(path: str | None) -> dict:
    if not path:
        return {}

    import yaml

    with open(path) as fh:
        return yaml.safe_load(fh) or {}


# YAML path -> argparse destination.
CONFIG_MAP = {
    "seed": "seed",
    "data.source": "source",
    "data.raw_path": "raw",
    "split.n_splits": "folds",
    "split.n_repeats": "repeats",
    "features.set": "feature_set",
    "quantum.n_qubits": "n_qubits",
    "quantum.depth": "depth",
    "quantum.shots": "shots",
    "quantum.entangler": "entangler",
    "kernel.reps": "reps",
    "kernel.entanglement": "entanglement",
    "kernel.C": "C",
    "kernel.max_samples": "max_samples",
    "training.epochs": "epochs",
    "training.lr": "lr",
    "training.batch_size": "batch_size",
    "training.gradient_method": "gradient_method",
    "report.ledger": "ledger",
}


def _dig(cfg: dict, dotted: str):
    cur = cfg

    for part in dotted.split("."):
        if not isinstance(cur, dict) or part not in cur:
            return None, False

        cur = cur[part]

    return cur, True


def _subparser_for(parser, cmd: str):
    """Return the command subparser."""

    for action in parser._actions:
        if isinstance(action, argparse._SubParsersAction):
            return action.choices.get(cmd)

    return None


def _apply_config(args, parser) -> list[str]:
    """Overlay YAML values onto arguments left at parser defaults.

    Precedence:
        command line > config file > parser default
    """

    cfg = _load_config(getattr(args, "config", None))
    sp = _subparser_for(parser, getattr(args, "cmd", None))

    if not cfg or sp is None:
        return []

    sentinel = object()
    defaults = {a.dest: a.default for a in sp._actions}

    applied = []

    for dotted, dest in CONFIG_MAP.items():
        if dest not in defaults or not hasattr(args, dest):
            continue

        # Explicit command-line values always win.
        if getattr(args, dest) != defaults.get(dest, sentinel):
            continue

        val, found = _dig(cfg, dotted)

        if found and val != defaults[dest]:
            setattr(args, dest, val)
            applied.append(f"{dotted}={val!r}")

    return applied


# ------------------------------------------------------------------ dataset
def _load_frame(a):
    """Load and validate the raw 70k cardiovascular dataset."""

    from qheart import schema as S
    from qheart.data import load

    raw = Path(getattr(a, "raw", "data/raw/cardio_train.csv"))

    if not raw.exists():
        print(
            f"missing {raw}\n"
            f"  run: bash scripts/fetch_data.sh\n"
            f"  expected the 70,000-row cardiovascular dataset at this path",
            file=sys.stderr,
        )
        raise SystemExit(2)

    df = load(
        getattr(a, "source", "cardio_70000"),
        raw,
    )

    S.validate(df)

    return df

    
def _design_matrix(a):
    raw = _load_frame(a)

    from qheart import schema as S
    from qheart.features.clinical import add_clinical_features
    from qheart.features.select import CANDIDATE_FEATURES

    # Keep the raw 70k cardiovascular feature space here.
    # ClinicalRepresentation performs the deterministic clinical
    # feature engineering inside each CV training fold.
    Xdf = raw.loc[:, S.FEATURES].copy()

    y = raw[S.TARGET].to_numpy(dtype=int)

    # Derived frame is retained for audit/reporting/display only.
    clinical = add_clinical_features(raw)

    return Xdf, y, clinical, list(CANDIDATE_FEATURES)


def _n_qubits_dense(n_features: int) -> int:
    try:
        from qheart.quantum.encodings import n_qubits_for

        return n_qubits_for(
            n_features,
            "dense_angle",
        )

    except Exception:
        return (n_features + 1) // 2


# ------------------------------------------------------------------ scoring
def _score(
    a,
    name,
    factory,
    X,
    y,
    *,
    n_params=None,
    extra=None,
    label=None,
    groups=None,
):
    """Run one model through the shared harness and append it to the ledger.

    Every reported number goes through this function. One CV loop, one threshold
    rule, one ledger: if a model is scored some other way its numbers are not
    comparable, and a table of numbers that are not comparable is worse than
    no table.
    """
    from qheart.eval.harness import append_to_ledger, evaluate

    res = evaluate(
        factory,
        X,
        y,
        model_name=label or name,
        groups=groups,
        n_splits=a.folds,
        n_repeats=a.repeats,
        seed=a.seed,
        n_trainable_params=n_params,
        config={
            "source": a.source,
            "feature_set": a.feature_set,
            "seed": a.seed,
            "folds": a.folds,
            "repeats": a.repeats,
            **(extra or {}),
        },
    )
    append_to_ledger(res, a.ledger)
    return res


# ------------------------------------------------------------------ commands
def cmd_schema(args):
    from qheart import schema as S

    print("Target:")
    print(f"  {S.TARGET}")

    print("\nNumeric features:")
    for name in S.NUMERIC:
        print(f"  - {name}")

    print("\nBinary features:")
    for name in S.BINARY_NUMERIC:
        print(f"  - {name}")

    print("\nCategorical features:")
    for name in S.CATEGORICAL:
        categories = S.CATEGORIES.get(name, [])
        print(f"  - {name}: {categories}")

    print("\nAll columns:")
    for name in S.ALL_COLUMNS:
        print(f"  - {name}")

    return 0


def cmd_models(a) -> int:
    from qheart.models import registry

    print(registry.describe())

    return 0


def cmd_params(a) -> int:
    from qheart.params import count_circuit_params, size_control_reducer

    c = count_circuit_params(
        a.n_qubits,
        a.depth,
    )

    print(c)
    print()

    print(
        size_control_reducer(
            c.trainable,
            d_in=a.d_in,
            d_out=a.n_qubits,
        ).summary()
    )

    print()

    vgg_total = 138_357_544
    vgg_conv = 14_714_688
    resnet = 25_636_712

    print(
        f"For scale: the VGG16 convolutional base is {vgg_conv:,} "
        f"parameters ({vgg_total:,} for the full network), and "
        f"ResNet50 is {resnet:,}."
    )

    print(
        f"This circuit is {vgg_conv // c.trainable:,}x smaller than "
        f"the VGG16 feature extractor it stands in for, and "
        f"{vgg_total // c.trainable:,}x smaller than the full network."
    )

    return 0


def cmd_budget(a) -> int:
    from qheart.quantum.budget import estimate_kernel_cost

    n_test = a.n_samples // a.folds
    n_train = a.n_samples - n_test

    print(
        estimate_kernel_cost(
            n_train,
            n_test,
            seconds_per_eval=a.seconds_per_eval,
            folds=a.folds * a.repeats,
        ).report()
    )

    return 0


def cmd_data(a) -> int:
    from qheart import schema as S

    df = _load_frame(a)

    PROCESSED.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    if PROCESSED.exists() and not a.force:
        print(
            f"{PROCESSED} exists; pass --force to overwrite"
        )

    else:
        try:
            df.to_parquet(PROCESSED)
            print(f"wrote {PROCESSED}")

        except Exception as e:
            # pyarrow is optional; CSV is a valid fallback.
            alt = PROCESSED.with_suffix(".csv")

            df.to_csv(
                alt,
                index=False,
            )

            print(
                f"parquet unavailable ({type(e).__name__}); "
                f"wrote {alt} instead"
            )

    print(
        f"{len(df)} rows x {df.shape[1]} columns, "
        f"prevalence {df[S.TARGET].mean():.3f}"
    )

    print(f"target: {S.TARGET}")

    print(
        "target counts: "
        f"{df[S.TARGET].value_counts().sort_index().to_dict()}"
    )

    print(
        f"missing values: {int(df.isna().sum().sum())}"
    )

    return 0


def cmd_audit(a) -> int:
    from qheart.data.audit import audit, audit_report, write

    r = audit(_load_frame(a))

    print(audit_report(r))

    j, m = write(
        r,
        Path(a.outdir) / "runs",
    )

    print(f"wrote {j}")
    print(f"wrote {m}")

    print(
        "\nRead the warnings section before writing any model code. "
        "Every one of them is a number in your report that would "
        "otherwise be wrong."
    )

    return 0

def _feature_group_ids(df):
    """Return deterministic group IDs for feature-identical observations.

    Groups are defined from the raw model-input features, not from the target.
    This prevents identical feature vectors from appearing in both train and
    test folds while preserving the generic evaluation harness.
    """
    from qheart import schema as S

    if not all(col in df.columns for col in S.FEATURES):
        missing = [col for col in S.FEATURES if col not in df.columns]
        raise ValueError(
            "Cannot construct duplicate-safe groups; missing raw feature "
            f"columns: {missing}"
        )

    # pandas' row hash is deterministic for a fixed dataframe representation.
    # Include index=False semantics by hashing only the feature columns.
    return df.loc[:, S.FEATURES].pipe(
        lambda frame: frame.apply(
            lambda col: col.astype("object") if str(col.dtype) == "category" else col
        )
    ).pipe(
        lambda frame: __import__("pandas").util.hash_pandas_object(
            frame, index=False
        ).to_numpy(dtype="uint64")
    )


def cmd_baselines(a) -> int:
    from qheart.models import registry

    X, y, df, cols = _design_matrix(a)

    # The definitive 70k benchmark uses feature-group-aware CV.
    # Identical feature vectors are never allowed to cross train/test folds.
    groups = _feature_group_ids(df)

    n_groups = len(set(groups.tolist()))
    print(
        f"{len(y)} rows, {len(cols)} features, prevalence {y.mean():.3f}, "
        f"{n_groups} feature groups, "
        f"{a.folds}x{a.repeats} = {a.folds * a.repeats} fits per model"
    )
    print(
        "split strategy: repeated group-stratified CV "
        "(feature-identical groups isolated)"
    )

    names = a.models or [
        n for n in registry.classical_models()
        if n != "control_c"
    ]

    for n in names:
        _score(
            a,
            n,
            registry.build(n),
            X,
            y,
            groups=groups,
            extra={
                "split_strategy": "repeated_group_stratified",
                "group_definition": "feature_identical_raw_features",
                "n_feature_groups": n_groups,
            },
        )

    print(f"\nledger -> {a.ledger}")
    print(
        "These are the yardstick. A quantum result that does not beat them is "
        "a result, not a failure -- but only if the yardstick was built first."
    )
    return 0


def cmd_kernel(a) -> int:
    """Run the quantum-kernel experiment.

    NOTE:
        The complete 70k dataset cannot be used to build a full
        quantum Gram matrix. max_samples is therefore a deliberate
        computational budget, not a hidden dataset reduction.
    """

    import numpy as np

    from qheart.quantum.budget import (
        estimate_kernel_cost,
        guard_kernel_size,
    )
    from qheart.quantum.kernel import QuantumKernel, quantum_svc

    Xdf, y, _, cols = _design_matrix(a)

    # Kernel experiments require a fixed numeric representation.
    #
    # This command is intentionally separate from the fold-safe
    # model evaluation path because a precomputed Gram matrix is
    # itself an expensive global object.
    #
    # The representation must be produced by a leakage-safe
    # transformer before this command is considered final.
    from qheart.preprocess.pipeline import (
        build_clinical_representation,
    )

    representation = build_clinical_representation(
        feature_names=cols,
        output="angles",
    )

    X = representation.fit_transform(
        Xdf,
        y,
    )

    n, d = X.shape

    guard_kernel_size(
        n,
        a.max_samples,
    )

    print(
        f"kernel representation: {n} rows x {d} features"
    )

    print(
        estimate_kernel_cost(
            n,
            folds=1,
        ).report()
    )

    print()

    k = QuantumKernel(
        n_qubits=d,
        reps=a.reps,
        entanglement=a.entanglement,
        shots=a.shots,
        max_samples=a.max_samples,
    )

    k.precompute(X)
    k.sanity_check()

    # The model's X is a column of row indices because the Gram
    # matrix is already precomputed.
    idx = np.arange(
        n,
        dtype=float,
    ).reshape(-1, 1)

    _score(
        a,
        "qkernel_zz",
        lambda: quantum_svc(
            k,
            np.arange(n),
            C=a.C,
        ),
        idx,
        y,
        extra={
            "reps": a.reps,
            "entanglement": a.entanglement,
            "C": a.C,
            "shots": a.shots,
            "n_qubits": d,
        },
    )

    print(
        "\nThe Gram matrix is cached by content hash."
    )

    return 0


def cmd_vqc(a) -> int:
    from qheart.models import registry
    from qheart.params import count_circuit_params

    Xdf, y, _, cols = _design_matrix(a)

    # Determine dimensionality from the fold-safe representation.
    #
    # The selector is expected to produce the compact quantum input
    # dimension configured for the experiment.
    d = 8

    n_q = _n_qubits_dense(d)

    c = count_circuit_params(
        n_q,
        a.depth,
    )

    print(
        f"{d} compact features -> {n_q} qubits "
        f"at 2 features per qubit (dense angle)"
    )

    print(c)

    print(
        f"plus one output bias -> "
        f"{c.trainable + 1} trainable parameters "
        f"({(c.trainable + 1) * 4} bytes at fp32)"
    )

    if a.gradient_method == "parameter-shift":
        print(
            "parameter-shift costs 2 evaluations per parameter "
            "per step: "
            f"{2 * (c.trainable + 1)} evaluations per step per sample."
        )

    print()

    shared = dict(
        n_features=d,
        depth=a.depth,
        seed=a.seed,
        entangler=a.entangler,
    )

    _score(
        a,
        "vqc_dense",
        registry.build(
            "vqc_dense",
            epochs=a.epochs,
            lr=a.lr,
            batch_size=a.batch_size,
            gradient_method=a.gradient_method,
            **shared,
        ),
        Xdf,
        y,
        n_params=c.trainable + 1,
        extra={
            "depth": a.depth,
            "epochs": a.epochs,
            "lr": a.lr,
            "gradient_method": a.gradient_method,
            "n_qubits": n_q,
        },
    )

    _score(
        a,
        "hybrid_extractor",
        registry.build(
            "hybrid_extractor",
            trainable=False,
            **shared,
        ),
        Xdf,
        y,
        extra={
            "depth": a.depth,
            "trainable_extractor": False,
            "n_qubits": n_q,
        },
    )

    print(
        "\nThe extractor is frozen, so its trainable parameters "
        "are the head's alone."
    )

    print(
        "Now run `make control` -- neither row above is reportable "
        "without it."
    )

    return 0


def cmd_control(a) -> int:
    from qheart.eval.stats import mcnemar
    from qheart.models import registry
    from qheart.params import (
        count_circuit_params,
        size_control_reducer,
    )

    Xdf, y, _, cols = _design_matrix(a)

    d = 8

    c = count_circuit_params(
        a.n_qubits,
        a.depth,
    )

    s = size_control_reducer(
        c.trainable,
        d_in=d,
        d_out=a.n_qubits,
    )

    print(s.summary())

    print(
        "The control receives the same compact clinical "
        "representation as the quantum arm. Only the representation "
        "mechanism differs.\n"
    )

    runs = {}

    for label, hidden, n_params in (
        (
            "control_c_below",
            s.hidden_below,
            s.params_below,
        ),
        (
            "control_c_above",
            s.hidden_above,
            s.params_above,
        ),
    ):
        factory = registry.build(
            "control_c",
            d_in=d,
            d_out=a.n_qubits,
            target_params=c.trainable,
            hidden=hidden,
            seed=a.seed,
        )

        runs[label] = _score(
            a,
            "control_c",
            factory,
            Xdf,
            y,
            label=label,
            n_params=n_params,
            extra={
                "hidden": hidden,
                "matched_to": c.trainable,
            },
        )

    lo = runs["control_c_below"]
    hi = runs["control_c_above"]

    if (
        lo.oof_pred is not None
        and hi.oof_pred is not None
    ):
        r = mcnemar(
            y,
            lo.oof_pred,
            hi.oof_pred,
        )

        print(
            f"\nMcNemar, below ({s.params_below} params) "
            f"vs above ({s.params_above} params): "
            f"{r.n_discordant} discordant, "
            f"p={r.p_value:.4f} [{r.method}]"
        )

        print(r.verdict())

    print(
        "\nBoth brackets are in the ledger and both go in the report."
    )

    return 0


def cmd_compare(a) -> int:
    import pandas as pd

    from qheart.eval.stats import (
        corrected_resampled_ttest,
        holm_bonferroni,
    )

    from qheart.report.tables import (
        main_table,
        param_table,
        refuse_if_incomplete,
        to_markdown,
    )

    led = Path(a.ledger)

    if not led.exists():
        print(
            f"no ledger at {led}. Run `make baselines` first.",
            file=sys.stderr,
        )
        raise SystemExit(2)

    df = pd.read_csv(led)

    out = Path(a.outdir)
    out.mkdir(
        parents=True,
        exist_ok=True,
    )

    tbl = main_table(df)

    audit_json = (
        out
        / "runs"
        / "data_audit.json"
    )

    if audit_json.exists():
        r = json.loads(
            audit_json.read_text()
        )

        acc = (
            r.get("class_balance") or {}
        ).get(
            "majority_class_accuracy"
        )

        if acc is not None:
            tbl.attrs[
                "majority_class_accuracy"
            ] = acc

    refuse_if_incomplete(tbl)

    md = to_markdown(tbl)

    (
        out / "main_table.md"
    ).write_text(
        md + "\n"
    )

    print(md)

    if "n_trainable_params" in df.columns:
        counts = (
            df.dropna(
                subset=[
                    "n_trainable_params"
                ]
            )
            .groupby("model")[
                "n_trainable_params"
            ]
            .first()
        )

        rows = [
            {
                "model": m,
                "params": int(v),
            }
            for m, v in counts.items()
        ]

        if rows:
            pt = param_table(rows)

            (
                out / "param_table.md"
            ).write_text(
                pt.to_markdown(
                    index=False
                )
                + "\n"
            )

            print(
                "\n"
                + pt.to_markdown(
                    index=False
                )
            )

    # Paired comparison against strongest classical baseline.
    metric = "pr_auc"

    if (
        metric in df.columns
        and "model" in df.columns
    ):
        per = {
            m: g[metric].to_numpy(
                dtype=float
            )
            for m, g in df.groupby(
                "model"
            )
        }

        classical = [
            m
            for m in (
                "logreg",
                "svm_rbf",
                "rf",
                "xgboost",
                "mlp",
            )
            if m in per
        ]

        if classical:
            ref = max(
                classical,
                key=lambda m: per[m].mean(),
            )

            n_train = (
                int(df["n_train"].max())
                if "n_train" in df.columns
                else len(df)
            )

            n_test = max(
                1,
                int(
                    round(
                        n_train
                        / max(
                            a.folds - 1,
                            1,
                        )
                    )
                ),
            )

            pvals = {}
            deltas = {}

            for m, v in per.items():
                if (
                    m == ref
                    or v.size != per[ref].size
                ):
                    continue

                _, p, note = corrected_resampled_ttest(
                    v,
                    per[ref],
                    n_train,
                    n_test,
                )

                pvals[m] = p
                deltas[m] = float(
                    v.mean()
                    - per[ref].mean()
                )

            if pvals:
                print(
                    f"\nPaired comparison vs best "
                    f"classical baseline ({ref}) "
                    f"on {metric}, "
                    "Nadeau-Bengio corrected, "
                    "Holm-adjusted:"
                )

                for m, (
                    adj,
                    rej,
                ) in holm_bonferroni(
                    pvals
                ).items():
                    verdict = (
                        "significant"
                        if rej
                        else "not significant"
                    )

                    print(
                        f"  {m:20s} "
                        f"d={deltas[m]:+.4f}  "
                        f"p_adj={adj:.4f}  "
                        f"{verdict}"
                    )

                print(
                    f"  [{note}]"
                )

                print(
                    "  Folds share training data, "
                    "so these are corrected p-values."
                )

    try:
        from qheart.report.figures import save_all

        rows = [
            {
                "model": m,
                "params": int(v),
                metric: float(
                    per[m].mean()
                ),
            }
            for m, v in (
                df.dropna(
                    subset=[
                        "n_trainable_params"
                    ]
                )
                .groupby("model")[
                    "n_trainable_params"
                ]
                .first()
                .items()
            )
            if m in per
        ]

        paths = save_all(
            {
                "params": rows,
                "metric": metric,
            },
            out / "figures",
        )

        for p in paths:
            print(f"wrote {p}")

    except ImportError:
        print(
            "\nmatplotlib absent: tables written, "
            "figures skipped."
        )

    print(
        f"\nwrote {out / 'main_table.md'}"
    )

    return 0


# ------------------------------------------------------------------ parser
def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        "qheart",
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )

    sub = p.add_subparsers(
        dest="cmd",
        required=True,
    )

    def common(sp):
        sp.add_argument(
            "--source",
            default="cardio_70000",
        )

        sp.add_argument(
            "--raw",
            default="data/raw/cardio_train.csv",
        )

        sp.add_argument(
            "--feature-set",
            default="cardio_compact8",
            dest="feature_set",
        )

        sp.add_argument(
            "--folds",
            type=int,
            default=5,
        )

        sp.add_argument(
            "--repeats",
            type=int,
            default=5,
        )

        sp.add_argument(
            "--seed",
            type=int,
            default=DEFAULT_SEED,
        )

        sp.add_argument(
            "--ledger",
            default=str(LEDGER),
        )

        return sp

    sub.add_parser(
        "schema"
    ).set_defaults(fn=cmd_schema)

    sub.add_parser(
        "models"
    ).set_defaults(fn=cmd_models)

    sp = sub.add_parser("params")

    sp.add_argument(
        "--n-qubits",
        type=int,
        default=4,
        dest="n_qubits",
    )

    sp.add_argument(
        "--depth",
        type=int,
        default=6,
    )

    sp.add_argument(
        "--d-in",
        type=int,
        default=8,
        dest="d_in",
    )

    sp.set_defaults(fn=cmd_params)

    sp = sub.add_parser("budget")

    sp.add_argument(
        "--n-samples",
        type=int,
        default=70000,
        dest="n_samples",
    )

    sp.add_argument(
        "--folds",
        type=int,
        default=5,
    )

    sp.add_argument(
        "--repeats",
        type=int,
        default=5,
    )

    sp.add_argument(
        "--seconds-per-eval",
        type=float,
        default=0.004,
        dest="seconds_per_eval",
    )

    sp.set_defaults(fn=cmd_budget)

    sp = common(
        sub.add_parser("data")
    )

    sp.add_argument(
        "--force",
        action="store_true",
    )

    sp.set_defaults(fn=cmd_data)

    sp = common(
        sub.add_parser("audit")
    )

    sp.add_argument(
        "--outdir",
        default="results",
    )

    sp.set_defaults(fn=cmd_audit)

    sp = common(
        sub.add_parser("baselines")
    )

    sp.add_argument(
        "--models",
        nargs="*",
    )

    sp.set_defaults(fn=cmd_baselines)

    sp = common(
        sub.add_parser("kernel")
    )

    sp.add_argument(
        "--n-qubits",
        type=int,
        default=4,
        dest="n_qubits",
    )

    sp.add_argument(
        "--reps",
        type=int,
        default=2,
    )

    sp.add_argument(
        "--entanglement",
        default="linear",
    )

    sp.add_argument(
        "--shots",
        type=int,
        default=None,
    )

    sp.add_argument(
        "--C",
        type=float,
        default=1.0,
    )

    sp.add_argument(
        "--max-samples",
        type=int,
        default=2000,
        dest="max_samples",
    )

    sp.set_defaults(fn=cmd_kernel)

    sp = common(
        sub.add_parser("vqc")
    )

    sp.add_argument(
        "--n-qubits",
        type=int,
        default=4,
        dest="n_qubits",
    )

    sp.add_argument(
        "--depth",
        type=int,
        default=6,
    )

    sp.add_argument(
        "--epochs",
        type=int,
        default=60,
    )

    sp.add_argument(
        "--gradient-method",
        default="backprop",
        dest="gradient_method",
        choices=[
            "backprop",
            "parameter-shift",
        ],
    )

    sp.add_argument(
        "--lr",
        type=float,
        default=0.05,
    )

    sp.add_argument(
        "--batch-size",
        type=int,
        default=32,
        dest="batch_size",
    )

    sp.add_argument(
        "--entangler",
        default="ring",
        choices=[
            "ring",
            "linear",
            "all_to_all",
            "none",
        ],
    )

    sp.set_defaults(fn=cmd_vqc)

    sp = common(
        sub.add_parser("control")
    )

    sp.add_argument(
        "--n-qubits",
        type=int,
        default=4,
        dest="n_qubits",
    )

    sp.add_argument(
        "--depth",
        type=int,
        default=6,
    )

    sp.set_defaults(fn=cmd_control)

    sp = common(
        sub.add_parser("compare")
    )

    sp.add_argument(
        "--outdir",
        default="results",
    )

    sp.set_defaults(fn=cmd_compare)

    # Every subcommand accepts --config.
    for sp in sub.choices.values():
        sp.add_argument(
            "--config",
            default=None,
            metavar="YAML",
            help=(
                "YAML config; explicit flags take "
                "precedence over it"
            ),
        )

    return p


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()

    a = parser.parse_args(argv)

    applied = _apply_config(
        a,
        parser,
    )

    if applied:
        print(
            f"config {a.config}: "
            + ", ".join(applied)
        )

    return int(
        a.fn(a) or 0
    )


if __name__ == "__main__":
    raise SystemExit(main())