"""An exact statevector simulator in ~200 lines of NumPy. No PennyLane, no Qiskit.

Why this exists, since "write your own simulator" is normally bad advice:

1. **The quantum install breaks.** It is the stated premise of this subpackage that
   the classical half keeps running when pennylane or qiskit-aer fails to build.
   This module extends that promise to the quantum models themselves: every circuit
   in this project can be executed, tested and demoed with numpy alone.
2. **It makes the physics testable.** ``pennylane`` is a black box in a unit test --
   if an expectation value is wrong you cannot tell whether the bug is yours. Here
   every gate is a few lines, so ``tests/`` can compare a circuit against a
   brute-force dense-matrix construction and localise the error.
3. **At 4-10 qubits it is faster than a framework.** The state is a length-2^n
   complex vector; applying a single-qubit gate is one reshape and one einsum. No
   graph construction, no device round-trip. The DCQF extractor evaluates one
   circuit per sample, so per-circuit overhead dominates the total runtime.

The limit is honest: exact simulation is O(2^n) memory. 20 qubits is 16 MB and fine,
30 qubits is 16 GB and not. ``MAX_QUBITS`` refuses past a size that would swap, and
``guard_qubits`` explains rather than dying with a MemoryError.

**This is a simulator, not a device.** It is noiseless and gives exact expectation
values, i.e. the infinite-shot limit. Real hardware has finite shots and decoherence,
which is what ``qheart.quantum.noise`` and ``shots=`` below are for -- a result
quoted from this module should say "exact simulation", never "quantum hardware".

Convention: qubit 0 is the most significant bit, so basis state |q0 q1 ... q_{n-1}>
has index sum(q_i * 2^(n-1-i)). This matches Qiskit's ``reverse_bits`` ordering and
the ordering used when printing counts; get it backwards and every correlation
observable silently pairs the wrong variables.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Iterable, Sequence

import numpy as np

__all__ = ["State", "MAX_QUBITS", "guard_qubits", "z_expectation",
           "z_string_expectations", "probabilities", "sample_counts",
           "expectations_from_counts"]

MAX_QUBITS = 22          # 2^22 complex128 = 64 MB. Past this, refuse and explain.

_SQRT_HALF = 1.0 / np.sqrt(2.0)


def guard_qubits(n: int) -> None:
    """Refuse a state vector that would exhaust memory, with the arithmetic shown."""
    if n < 1:
        raise ValueError("need at least 1 qubit")
    if n > MAX_QUBITS:
        gb = (2 ** n) * 16 / 1e9
        raise ValueError(
            f"{n} qubits needs a 2^{n} complex128 vector = {gb:.1f} GB. This simulator "
            f"is exact, so cost is exponential and there is no way around it. Cap is "
            f"{MAX_QUBITS} qubits. For the DCQF encoding, reduce the feature count "
            f"(one qubit per feature) or run on hardware via qiskit."
        )


@dataclass
class State:
    """A pure state on ``n`` qubits, stored as a flat complex vector.

    Gates mutate in place and return ``self``, so circuits read as a chain:

        State(4).h_all().rz(0, 0.3).cnot(0, 1).z_expectation([0, 1])
    """

    n: int
    vec: np.ndarray = field(default=None, repr=False)

    def __post_init__(self) -> None:
        guard_qubits(self.n)
        if self.vec is None:
            self.vec = np.zeros(2 ** self.n, dtype=np.complex128)
            self.vec[0] = 1.0                      # |00...0>
        else:
            self.vec = np.asarray(self.vec, dtype=np.complex128).ravel()
            if self.vec.size != 2 ** self.n:
                raise ValueError(f"vector of size {self.vec.size} is not 2^{self.n}")

    # ---------------------------------------------------------------- internals
    def _as_tensor(self) -> np.ndarray:
        """View the flat vector as an n-dimensional (2,)*n tensor. No copy."""
        return self.vec.reshape((2,) * self.n)

    def _apply_1q(self, gate: np.ndarray, q: int) -> "State":
        """Contract a 2x2 gate into axis ``q``.

        ``tensordot`` puts the contracted axis first, so ``moveaxis`` returns it to
        position q. Forgetting that reorders the qubits and every subsequent gate
        acts on the wrong wire -- the state stays normalised, so nothing complains.
        """
        if not 0 <= q < self.n:
            raise IndexError(f"qubit {q} out of range for {self.n} qubits")
        t = self._as_tensor()
        t = np.tensordot(gate, t, axes=([1], [q]))
        self.vec = np.moveaxis(t, 0, q).ravel()
        return self

    def _apply_diagonal(self, phases: np.ndarray) -> "State":
        """Multiply by a diagonal unitary given as per-basis-state phases.

        Every gate generated by a Pauli-Z string is diagonal in the computational
        basis, which is the whole reason the DCQF Hamiltonian evolution is cheap:
        exp(-i theta Z_a Z_b Z_c ...) costs one elementwise multiply regardless of
        how many qubits the string touches.
        """
        self.vec = self.vec * phases
        return self

    # ---------------------------------------------------------------- 1q gates
    def h(self, q: int) -> "State":
        return self._apply_1q(np.array([[_SQRT_HALF, _SQRT_HALF],
                                        [_SQRT_HALF, -_SQRT_HALF]], dtype=np.complex128), q)

    def h_all(self) -> "State":
        """Prepare |+>^n, the ground state of the transverse-field Hamiltonian
        H_i = -sum_j X_j and therefore the DCQF protocol's initial state."""
        for q in range(self.n):
            self.h(q)
        return self

    def rx(self, q: int, theta: float) -> "State":
        c, s = np.cos(theta / 2), -1j * np.sin(theta / 2)
        return self._apply_1q(np.array([[c, s], [s, c]], dtype=np.complex128), q)

    def ry(self, q: int, theta: float) -> "State":
        c, s = np.cos(theta / 2), np.sin(theta / 2)
        return self._apply_1q(np.array([[c, -s], [s, c]], dtype=np.complex128), q)

    def rz(self, q: int, theta: float) -> "State":
        e = np.exp(-0.5j * theta)
        return self._apply_1q(np.array([[e, 0], [0, np.conj(e)]], dtype=np.complex128), q)

    # ---------------------------------------------------------------- 2q gates
    def cnot(self, control: int, target: int) -> "State":
        if control == target:
            raise ValueError("CNOT needs two distinct qubits")
        for q in (control, target):
            if not 0 <= q < self.n:
                raise IndexError(f"qubit {q} out of range for {self.n} qubits")
        t = self._as_tensor().copy()
        # Slice the subspace where control == 1 and swap the target amplitudes.
        idx_c1 = [slice(None)] * self.n
        idx_c1[control] = 1
        sub = t[tuple(idx_c1)]
        # In ``sub`` the control axis is gone, so the target axis shifts left by one
        # if it sat after the control. Off-by-one here is the classic silent bug.
        tgt_axis = target - 1 if target > control else target
        t[tuple(idx_c1)] = np.flip(sub, axis=tgt_axis)
        self.vec = t.ravel()
        return self

    # ------------------------------------------------- Pauli-Z string evolution
    def _z_string_signs(self, qubits: Sequence[int]) -> np.ndarray:
        """+-1 eigenvalue of prod_{i in qubits} Z_i for every basis state.

        Computed with bit tricks over all 2^n indices at once rather than a Python
        loop, because this is called once per Hamiltonian term per sample.
        """
        qubits = list(dict.fromkeys(int(q) for q in qubits))   # dedupe, keep order
        for q in qubits:
            if not 0 <= q < self.n:
                raise IndexError(f"qubit {q} out of range for {self.n} qubits")
        idx = np.arange(2 ** self.n, dtype=np.int64)
        parity = np.zeros(2 ** self.n, dtype=np.int64)
        for q in qubits:
            bit = (idx >> (self.n - 1 - q)) & 1        # qubit 0 is the top bit
            parity ^= bit
        return 1.0 - 2.0 * parity                       # 0 -> +1, 1 -> -1

    def rzz_string(self, qubits: Sequence[int], theta: float) -> "State":
        """exp(-i theta/2 * prod_i Z_i) for an arbitrary-length Z string.

        This single method covers every term of the DCQF encoding Hamiltonian: a
        one-body field is a string of length 1, a two-body coupling length 2, a
        three-body coupling length 3. On hardware the same operation needs a CNOT
        ladder; here it is a diagonal phase, which is why the simulator handles
        k-local terms at no extra cost.
        """
        signs = self._z_string_signs(qubits)
        return self._apply_diagonal(np.exp(-0.5j * theta * signs))

    def rzz(self, a: int, b: int, theta: float) -> "State":
        return self.rzz_string([a, b], theta)

    def ryz_string(self, y_qubit: int, z_qubits: Sequence[int], theta: float) -> "State":
        """exp(-i theta/2 * Y_j (x) prod_{k in z_qubits} Z_k).

        This is the generator the counterdiabatic term actually needs. The first-order
        adiabatic gauge potential for a transverse-field-to-spin-glass sweep is built
        from [-X_j, c prod_{i in S} Z_i] = 2i c Y_j prod_{i in S, i != j} Z_i -- one Y
        on the site being kicked, Z on the rest of the coupled subset. Verified
        against dense matrices in the tests.

        Implemented by basis change rather than by exponentiating a 2^n matrix:
        with U = Rx(-pi/2) we have U Z U^dag = Y, so

            exp(-i th/2 Y_j (x) Zs) = U_j exp(-i th/2 Z_j (x) Zs) U_j^dag

        and conjugating the (diagonal, hence cheap) Z-string rotation turns its Z into
        a Y. Cost is two extra single-qubit gates regardless of how many qubits the
        string spans.

        Note the gate order. Reading ``U M U^dag`` right-to-left as it acts on a ket,
        ``U^dag = Rx(+pi/2)`` is applied *first*. Writing the operators down in the
        order they appear in the formula gives the inverse rotation and is the reason
        the first version of this method failed its test.
        """
        z_qubits = [int(q) for q in z_qubits if int(q) != int(y_qubit)]
        self.rx(y_qubit, +np.pi / 2)                       # U^dag, acts first
        self.rzz_string([int(y_qubit), *z_qubits], theta)
        self.rx(y_qubit, -np.pi / 2)                       # U:  Z -> Y
        return self

    # ---------------------------------------------------------------- readout
    def probabilities(self) -> np.ndarray:
        p = np.abs(self.vec) ** 2
        s = p.sum()
        if not np.isfinite(s) or s <= 0:
            raise FloatingPointError("state has zero or non-finite norm")
        return p / s                     # renormalise against float drift only

    def norm(self) -> float:
        return float(np.linalg.norm(self.vec))

    def z_expectation(self, qubits: Sequence[int]) -> float:
        """<prod_{i in qubits} Z_i>, exact (infinite-shot limit)."""
        return float(np.dot(self.probabilities(), self._z_string_signs(qubits)))

    def z_string_expectations(self, strings: Iterable[Sequence[int]]) -> np.ndarray:
        """Expectation of many Z strings from ONE probability vector.

        All Pauli-Z strings commute, so they are simultaneously measurable and a
        single circuit execution suffices for all of them. The DCQF paper relies on
        exactly this ("no additional circuits are required because all measured
        observables commute"), and it is why the method is cheap: one circuit per
        sample, hundreds of features out.
        """
        p = self.probabilities()
        return np.array([float(np.dot(p, self._z_string_signs(s))) for s in strings],
                        dtype=float)

    def sample_counts(self, shots: int, seed: int = 0) -> np.ndarray:
        """Multinomial sample of basis-state counts -- the finite-shot reality.

        Use this, not the exact path, when claiming a hardware-comparable result.
        Shot noise on an expectation value is ~1/sqrt(shots): at the paper's 8000
        shots that is ~0.011, which is larger than several of the feature
        differences being learned from.
        """
        if shots < 1:
            raise ValueError("shots must be >= 1")
        rng = np.random.default_rng(seed)
        return rng.multinomial(shots, self.probabilities())


def probabilities(state: State) -> np.ndarray:
    return state.probabilities()


def z_expectation(state: State, qubits: Sequence[int]) -> float:
    return state.z_expectation(qubits)


def z_string_expectations(state: State, strings: Iterable[Sequence[int]]) -> np.ndarray:
    return state.z_string_expectations(strings)


def sample_counts(state: State, shots: int, seed: int = 0) -> np.ndarray:
    return state.sample_counts(shots, seed)


def expectations_from_counts(counts: np.ndarray, n: int,
                             strings: Iterable[Sequence[int]]) -> np.ndarray:
    """Z-string expectations from raw shot counts, as done on hardware.

    Mirrors the paper's procedure ("expectation values were computed directly from
    the raw measurement counts") so a simulated result and a hardware result can be
    produced by the same downstream code.
    """
    counts = np.asarray(counts, dtype=float)
    if counts.size != 2 ** n:
        raise ValueError(f"counts has size {counts.size}, expected 2^{n}")
    total = counts.sum()
    if total <= 0:
        raise ValueError("no shots recorded")
    p = counts / total
    idx = np.arange(2 ** n, dtype=np.int64)
    out = []
    for s in strings:
        parity = np.zeros(2 ** n, dtype=np.int64)
        for q in dict.fromkeys(int(x) for x in s):
            parity ^= (idx >> (n - 1 - q)) & 1
        out.append(float(np.dot(p, 1.0 - 2.0 * parity)))
    return np.array(out, dtype=float)
